name: TypeDoc

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use cached node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            nodeModules-

      - name: Install Dependencies
        run: npm ci

      - name: Build Docs
        run: npm run doc

      - name: Deploy
        uses: cloudflare/pages-action@1
        with:
          accountId: 620ff29bbd515d2848f5306578bd1d1d
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_TOKEN }}
          projectName: featherjs
          directory: docs
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
